# Generated by Django 4.1.5 on 2023-01-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('experiance', models.CharField(max_length=100)),
                ('expetarea', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.IntegerField()),
            ],
        ),
    ]
