# Generated by Django 4.1.5 on 2023-01-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
