# Generated by Django 4.1.5 on 2023-01-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_information_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(null=True, upload_to='BASE_DIR'),
        ),
    ]
