# Generated by Django 4.1.5 on 2023-01-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_information_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(null=True, upload_to='\\database_files\\database_images'),
        ),
    ]
