# Generated by Django 4.1.5 on 2023-01-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_alter_information_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(null=True, upload_to='static\\database_images'),
        ),
    ]
