# Generated by Django 4.1.5 on 2023-01-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_alter_information_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='pdf',
            field=models.FileField(null=True, upload_to='static\\database_doc'),
        ),
    ]
