# Generated by Django 4.1.5 on 2023-01-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_information_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='mob',
            field=models.CharField(max_length=20),
        ),
    ]
